# http://localhost:8082/actuator/circuitbreakers

server:
  port: 8084

spring:
  application:
    name: clientms

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://z1:8761/eureka, http://z2:8762/eureka, http://z3:8763/eureka
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 8
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: COUNT_BASED
        waitDurationInOpenState: 30
        failureRateThreshold: 50
        minimumNumberOfCalls: 4
    instances:
      bookmsclient:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransferFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
      issuermsclient:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransferFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED